const selectionSets = {
  "<ClassDecl>": ["public", "private", "default"],
  "<Extra>": ["{"],
  "<InterfaceIDList>": ["ID"],
  "<listID>": ["{"],
  "<ClassBody>": ["{"],
  "<ClassBodyDecl>": ["   "],
  "<C>": ["{", "void", "int", "bool", "float", "char", "string"],
  "<L>": [],
  "<Parameters>": [],
  "<parameter_list>": [],
  "<Parameter>": ["DT"],
  "<return_type>": ["void", "int", "float", "char", "bool", "string"],
  "<Main_Func>": ["public", "private"],
  "<Attributes>": ["DT", "ArrayList", "HashMap"],
  "<A>": ["ID", "["],
  "<abstract_fun>": ["public"],
  "<AM>": ["public", "private"],
  "<AMO>": ["Static"],
  "<ClassAccMod>": ["public", "private", "default"],
  "<ClassNonAccMod>": ["class"],
  "<Body>": ["}", "break"],
  "<SST>": [
    "public",
    "private",
    "while",
    "if",
    "do",
    "for",
    "switch",
    "try",
    "ID",
  ],
  "<MST>": ["}", "break"],
  "<S>": ["."],
  "<S2>": [
    "ID",
    "add",
    "get",
    "set",
    "remove",
    "clear",
    "size",
    "put",
    "length",
    "FieldID",
  ],
  "<AM_st>": ["public", "private"],
  "<NS>": ["Static", "DT", "ArrayList", "Hashmap", "ID"],
  "<ST>": ["DT", "ArrayList", "Hashmap", "ID"],
  "<interface_Dec>": ["interface"],
  "<interface_Body>": ["}"],
  "<NT>": ["Static", "DT", "ID"],
  "<Interface_Var_init>": ["Static", "DT"],
  "<Init>": ["DT"],
  "<Fun_Head>": ["ID"],
  "<obj_Dec>": ["ObjectType"],
  "<O1>": [";"],
  "<Var>": ["ID"],
  "<V>": [",", ";", "="],
  "<Var_Dec>": [",", ";"],
  "<V2>": [
    "this",
    "ID",
    "int_const",
    "bool_const",
    "double_const",
    "str_const",
    "char_const",
    "!",
  ],

  "<Array>": ["["],
  "<list>": [",", "="],
  "<array_init>": [";", "="],
  "<Al>": ["{", "new"],
  "<list_values>": ["}"],
  "<array_use>": ["ID"],
  "<array_change_value>": [";", "="],
  "<WDT>": ["Integer", "String", "Boolean", "Character", "Float"],
  "<arraylist>": ["ArrayList"],
  "<HashMap>": ["HashMap"],
  "<While_St>": ["while"],
  "<Do_while_St>": ["do"],
  "<if_else>": ["if"],
  "<O_if_Else>": ["else", "$"],
  "<O_Else>": ["$"],
  "<for_St>": ["for"],
  "<F2>": [";"],
  "<F3>": ["ID", "++", "--"],
  "<F4>": ["++", "--", "="],
  "<inc_dec_Op>": ["++", "--"],

  "<assign_St>": [""],
  "<assign_left>": ["="],
  "<assign_right>": [
    "this",
    "ID",
    "int_const",
    "bool_const",
    "double_const",
    "str_const",
    "char_const",
    "!",
  ],
  "<Z>": ["ε"],
  "<func_St>": ["("],
  "<Parameters>": [")"],
  "<parameter_list>": [")"],
  "<Parameter>": ["DT"],
  "<return_type>": ["void", "int", "float", "char", "bool", "string"],
  "<func_call>": ["("],
  "<Arguments>": [
    "this",
    "ID",
    "int_const",
    "bool_const",
    "double_const",
    "str_const",
    "char_const",
    "!",
  ],
  "<Switch_St>": ["Switch"],
  "<case_blocks>": ["}"],
  "<case_block>": ["case"],
  "<default_block>": ["default"],
  "<break_St>": ["break"],
  "<continue_St>": ["continue"],
  "<try_catch_block>": ["try"],
  "<catch_block>": ["catch"],
  "<finally_block>": ["$"],
  "<except_type>": ["ID", "Const"],
  "<IC>": ["ID", "Const"],

  "<Dot_St>": ["ID"],
  "<D1>": [
    "ID",
    "add",
    "get",
    "set",
    "remove",
    "clear",
    "size",
    "put",
    "length",
  ],
  "<Object_opertaions>": ["ID"],
  "<Object_operations_tail>": ["$"],
  "<array_operations>": ["length"],
  "<Operations>": ["add", "get", "set", "remove", "clear", "size", "put"],
  "<add_operation>": ["add"],
  "<get_operation>": ["get"],
  "<set_operation>": ["set"],
  "<remove_operation>": ["remove"],
  "<clear_operation>": ["clear"],
  "<size_operation>": ["size"],
  "<put_operation>": ["put"],
  "<index>": ["int_const"],
  "<OE>": [
    "this",
    "ID",
    "int_const",
    "bool_const",
    "double_const",
    "str_const",
    "char_const",
    "!",
  ],
  "<OE’>": [")", "]", ";", "$"],
  "<AE>": [
    "this",
    "ID",
    "int_const",
    "bool_const",
    "double_const",
    "str_const",
    "char_const",
    "!",
  ],
  "<AE’>": ["||", ")", "]", ";", "$"],
  "<R>": [
    "this",
    "ID",
    "int_const",
    "bool_const",
    "double_const",
    "str_const",
    "char_const",
    "!",
  ],
  "<R’>": ["&&", "||", ")", "]", ";", "$"],
  "<E>": [
    "this",
    "ID",
    "int_const",
    "bool_const",
    "double_const",
    "str_const",
    "char_const",
    "!",
  ],
  "<E’>": ["RO", "&&", "||", ")", "]", ";", "$"],
  "<T>": [
    "this",
    "ID",
    "int_const",
    "bool_const",
    "double_const",
    "str_const",
    "char_const",
    "!",
  ],
  "<T’>": ["PM", "RO", "&&", "||", ")", "]", ";", "$"],
  "<F>": [
    "this",
    "ID",
    "int_const",
    "bool_const",
    "double_const",
    "str_const",
    "char_const",
    "!",
  ],
  "<F1>": ["MDM", "PM", "RO", "&&", "||", ")", "]", ";", "$"],
  "<F5>": ["MDM", "PM", "RO", "&&", "||", ")", "]", ";", "$"],
  "<AL>": [")"],
  "<Argument>": [
    "this",
    "ID",
    "int_const",
    "bool_const",
    "double_const",
    "str_const",
    "char_const",
    "!",
  ],
  "<Next_Argument>": [")"],
  "<P>": ["ID"],
}
